# Chapter 14: Exception Handling

- try-except-finally
```python
try:
    x=int("abc")
except ValueError:
    print("Error")
finally:
    print("Done")
```
